---
galaxy_info:
  author: Daniele Riccucci
  description: A role to install and configure rclone
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - rclone
    - network
dependencies: []
