---
- name: ensure user exists
  user:
    name: "{{ config.user }}"

- name: ensue directory for config exists
  file:
    mode: 0775
    path: "{{ config.path | d(ansible_env.HOME ~ '/.config/rclone/rclone.conf') | dirname }}"
    owner: "{{ config.user }}"
    state: directory

- name: set up rclone config
  copy:
    content: |-
      {% for block in blocks | dict2items %}
      [{{ block.key }}]
      {% for element in block.value | dict2items %}
      {% if element.value == None %}
      {{ element.key }} =
      {% else %}
      {{ element.key }} = {{ element.value }}
      {% endif %}
      {% endfor %}

      {% endfor %}
    dest: "{{ config.path | d(ansible_env.HOME ~ '/.config/rclone/rclone.conf') }}"
    owner: "{{ config.user }}"
    mode: "0600"
  vars:
    blocks: "{{ config.blocks }}"
...
