---
- name: gather OS-specific variables
  include_vars:
    file: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - main.yml
      paths:
        - "vars"
  tags: "role::rclone.vars"

- name: import install.yml
  import_tasks: install.yml
  when: rclone__enabled

- name: include configure.yml
  include_tasks: configure.yml
  args:
    apply:
      tags: "role::rclone.configure"
  loop: "{{ rclone__configs }}"
  loop_control:
    loop_var: config
  when:
    - rclone__configure
    - rclone__configs != []
    - rclone__enabled
  tags: "role::rclone.configure"

- name: import remove.yml
  import_tasks: remove.yml
  when: not rclone__enabled
  become: yes
...
