---
- name: gather OS-specific variables
  include_vars:
    file: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - main.yml
      paths:
        - "vars"
  tags: "role::rclone.vars"

- import_tasks: install.yml
  when: rclone__enabled

- import_tasks: remove.yml
  when: not rclone__enabled
  become: yes
...
