---
- name: remove github module
  pip:
    name: github3.py
    state: absent
  tags: "role::rclone.pip"

- name: remove local facts
  file:
    path: /etc/ansible/facts.d/rclone.fact
    state: absent
  tags: "role::rclone.facts"

- name: remove files and man page
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ rclone__binary }}"
    - "{{ rclone__man_path ~ '/rclone.1' }}"

- name: check path empty
  command: "ls -A {{ item }}"
  changed_when: no
  failed_when: no
  check_mode: no
  register: rclone__dirs_empty
  loop:
    - /etc/ansible/facts.d
    - "{{ rclone__binary | dirname }}"
    - "{{ rclone__man_path }}"

- name: remove empty dir
  file:
    path: "{{ ls.item }}"
    state: absent
  when:
    - ls.stdout | length == 0
  loop: "{{ rclone__dirs_empty.results }}"
  loop_control:
    loop_var: ls

- include_tasks: remove_configs.yml
  loop: "{{ rclone__configs }}"
  loop_control:
    loop_var: config
  tags: "role::rclone.configure"
...
