---
- name: remove config
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ '~/.config/rclone/rclone.conf' | expanduser }}"
    - "{{ '~/.config/rclone' | expanduser }}"
    - "{{ '~/.rclone.conf' | expanduser }}"
    - "{{ '$XDG_CONFIG_HOME/rclone/rclone.conf' | expandvars }}"
    - "{{ config.path | d(ansible_env.HOME ~ '/.config/rclone/rclone.conf') }}"
    - "{{ config.path | d(ansible_env.HOME ~ '/.config/rclone/rclone.conf') | dirname }}"
  become: yes
  become_user: "{{ config.user }}"
