---
- name: Converge
  hosts: all
  roles:
    - role: rclone
      rclone__version: v1.50.0
      rclone__binary: /opt/rclone/rclone
      rclone__install_man: yes
      rclone__configure: yes
      rclone__configs:
        - user: root
          path: /root/.local/rclone/rclone.conf
          blocks:
            dropbox:
              type: dropbox
              app_key: ~
              app_secret: ~
              token: '{"access_token":"secret-token-","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
