---
- name: Converge
  hosts: all

  tasks:
    - import_role:
        name: rclone
      vars:
        rclone__configure: yes
        rclone__configs:
          - user: root
            blocks:
              openstack:
                type: swift
                env_auth: "true"
                user: username
                key: API_key_or_password
...
