---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu-xenial
    image: ubuntu:xenial
    dockerfile: ../Dockerfile.j2
  - name: ubuntu-bionic
    image: ubuntu:bionic
    dockerfile: ../Dockerfile.j2
  - name: ubuntu-focal
    image: ubuntu:focal
    dockerfile: ../Dockerfile.j2
  - name: debian-stretch
    image: debian:stretch
    dockerfile: ../Dockerfile.j2
  - name: debian-buster
    image: debian:buster
    dockerfile: ../Dockerfile.j2
  # - name: rpi3-ubuntu-bionic
  #   image: balenalib/raspberrypi3-ubuntu:bionic
  # - name: rpi3-debian-buster
  #   image: balenalib/raspberrypi3-debian:buster
  # - name: rpi4-ubuntu-bionic
  #   image: balenalib/raspberrypi4-64-ubuntu:bionic
  # - name: rpi4-debian-buster
  #   image: balenalib/raspberrypi4-64-debian:buster
  - name: centos-7
    image: centos:7
    dockerfile: ../Dockerfile.j2
  - name: centos-8
    image: centos:8
    dockerfile: ../Dockerfile.j2
  - name: fedora-32
    image: fedora:32
    dockerfile: ../Dockerfile.j2
  - name: fedora-33
    image: fedora:33
    dockerfile: ../Dockerfile.j2
provisioner:
  name: ansible
  env:
    ANSIBLE_DIFF_ALWAYS: 'True'
    ANSIBLE_SKIP_TAGS: "role::rclone.github"
    ANSIBLE_STDOUT_CALLBACK: yaml
  playbooks:
    converge: converge.yml
  ansible_args:
    - --verbose
verifier:
  name: ansible
  env:
    ANSIBLE_DIFF_ALWAYS: 'True'
    ANSIBLE_STDOUT_CALLBACK: yaml
...
