---
name: molecule test
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        ansible-version: [ '2.8.0', '2.9.0', '2.10.0' ]
        molecule-scenario: [ 'default', 'customized', 'remove', 'beta', 'github' ]

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'roles/rclone'

      - name: Setup Python v3
        uses: actions/setup-python@v2
        with:
          python-version: '~3.8'

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.2
        with:
          docker_version: 19.03
          docker_channel: stable

      - name: Install dependencies
        env:
          ANSIBLE_VERSION: ${{ matrix.ansible-version }}
        run: |
          pip install 'molecule[docker]' docker yamllint ansible-lint ansible~="${ANSIBLE_VERSION}"

      - name: Run molecule check
        env:
          MOLECULE_SCENARIO: ${{ matrix.molecule-scenario }}
        run: |
          molecule check --parallel -s "${MOLECULE_SCENARIO}"
        working-directory: ./roles/rclone

      - name: Run molecule test
        env:
          MOLECULE_SCENARIO: ${{ matrix.molecule-scenario }}
        run: |
          molecule test --parallel -s "${MOLECULE_SCENARIO}"
        working-directory: ./roles/rclone

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'roles/rclone'

      - name: Get YML Paths
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ./roles/rclone/meta/main.yml
          description: galaxy_info.description
        id: load_galaxy

      - name: Update repo description
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            github.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: "${{steps.load_galaxy.outputs.description}}"
            })
...
