---
name: Molecule Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        ansible-version: [ '2.7.0', '2.8.0', '2.9.0' ]
        molecule-scenario: [ 'default', 'customized' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '~3.8'

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 19.03
          docker_channel: stable

      - name: Install dependencies
        env:
          ANSIBLE_VERSION: ${{ matrix.ansible-version }}
        run: |
          pip install molecule docker ansible~="${ANSIBLE_VERSION}"

      - name: Test with molecule
        env:
          MOLECULE_SCENARIO: ${{ matrix.molecule-scenario }}
        run: |
          molecule test -s "${MOLECULE_SCENARIO}"
